version: "3.9"
services:
    redis:
        image: redis
        expose: 
            - 6379
    nginx:
        image: nginx
        expose: 
            - 80
    app:
        image: app
        build: ./src
        depends_on: 
            - redis
            - nginx
        ports: 
            - 8090:80