version: "3.9"
services:
    redis-srv:
        image: redis
        expose: 
            - 6379
        networks: 
            - my_net_v2
    nginx:
        image: nginx
        expose: 
            - 80
        networks: 
            - my_net_v2
    app:
        image: app
        build: ./src
        depends_on: 
            - redis-srv
            - nginx
        ports: 
            - 8090:80
        environment: 
            redis: redis-srv
        env_file: dev.env
        networks: 
            - my_net_v2
networks: 
    my_net_v2:
        driver: bridge
        attachable: true