apiVersion: v1
kind: ConfigMap
metadata:
  name: kuard-config
data:
  test_env: "Jakies value"
  demo: "pracuj.pl jest super!"
---
apiVersion: v1
kind: Pod
metadata:
  name: kuard
  labels:
    name: kuard
spec:
  containers:
  - name: kuard
    image: gcr.io/kuar-demo/kuard-amd64:1
    resources: {}
    env:
      - name: env1
        valueFrom:
          configMapKeyRef:
            key: demo
            name: kuard-config
      - name: demo
        valueFrom:
          configMapKeyRef:
            key: demo
            name: kuard-config
